### ISSUE TITLE
Cannot read property 'Collection' of undefined

### ISSUE THREAD

**Issue by joshperrin** [adtribute/pub-sub-lite#9]
I'm adding pub-sub-lite to my app, and I'm getting the following error, and can't figure out why, any ideas?

> TypeError: Cannot read property 'Collection' of undefined 
> at module (packages/maestroqadev:pub-sub-lite/lib/enhanced-methods/enhanced-methods-mutation-handlers-server.js:25:30)
> at fileEvaluate (packages/modules-runtime.js:336:7)
> at Module.require (packages/modules-runtime.js:238:14)
> at Module.moduleLink [as link (/Users/joshperrin/.meteor/packages/modules/.0.16.0.4ygf36.y0tn6++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:52:22)
> at module (packages/maestroqadev:pub-sub-lite/server.js:1:84)
> at fileEvaluate (packages/modules-runtime.js:336:7)
> at Module.require (packages/modules-runtime.js:238:14)
> at require (packages/modules-runtime.js:258:21)
> at /Users/joshperrin/Documents/GitHub/bluebird/.meteor/local/build/programs/server/packages/maestroqadev_pub-sub-lite.js:971:15
> at /Users/joshperrin/Documents/GitHub/bluebird/.meteor/local/build/programs/server/packages/maestroqadev_pub-sub-lite.js:976:3

**Comment by npvn** [comment]
Hi @joshperrin, sorry for the late reply. Could you please let me take a look at your `.meteor/packages`?
